### ISSUE TITLE
perf: uso de um hashtable para verificação das wallets 

### ISSUE THREAD

**Issue by pab-h** [lmajowka/btcgo#17]
Olá! 

Trago uma sugestão para melhora da performace: uso de um hashtable

Atualmente, para fazer a verificação se foi encontrado uma privateKey de uma wallet é dado pelo seguinte código:

```go
func worker(wallets *Wallets, privKeyChan <-chan *big.Int, resultChan chan<- *big.Int, wg *sync.WaitGroup) {
	defer wg.Done()
	for privKeyInt := range privKeyChan {
		address := btc_utils.CreatePublicHash160(privKeyInt)
		if Contains(wallets.Addresses, address) {
			select {
			case resultChan <- privKeyInt:
				return
			default:
				return
			}
		}
	}
}
```
especificamente, a função `Contains` em
```go
if Contains(wallets.Addresses, address) {
	select {
	case resultChan <- privKeyInt:
		return
	default:
		return
	}
}
```
Essa função, é implementada da seguinte forma: 
```go
func Contains(slice [][]byte, item []byte) bool {
	for _, a := range slice {
		if bytes.Equal(a, item) {
			return true
		}
	}
	return false
}
```
A [Complexidade de Tempo é linear, `O(n)`](https://pt.wikipedia.org/wiki/Complexidade_de_tempo) onde n, nesse caso é quantidade de `wallets.Addresses`. Por isso, nota-se uma melhora quando [nesse vídeo](https://youtu.be/0a5Cu32JfJs?si=vHTtKyS5AilX1SP_&t=440) deixa-se somente um endereço.

Uma forma de otimizar essa busca é usando [Tabelas de Dispersão(Hash Table)](https://pt.wikipedia.org/wiki/Tabela_de_dispers%C3%A3o) que tem como característica principal a busca em tempo constante, `O(1)`. Dado uma rápida lida da definição e da implementação dessa estrutura, é fácil ver como utilizar. Mas, vai aqui um resumo:
* Cria-se um função de hash para **mapear o `address` em uma key**;
* **Preenche-se** a tabela hash com os valores(hash gerado e `address`);
* Faz-se a busca pela chave. Se essa chave existir, então o `address` também existe.

Um estrutura _built in_ do go que facilitará essa implementação é o [map](https://go.dev/blog/maps)

Observação: Também é plemente possível, dado o uso do *map*, que a função de hash seja da seguinte forma **`address` -> `address`** pulando a necessidade de definição de uma função mais complexa.

Espero que tenha conseguido explicar bem a ideia.

Até.

**Comment by alexandrersa** [comment]
Ainda persiste este problema? @pab-h  Acredito que esse comportamento encontrava-se apenas em versões anteriores do código.

**Comment by pab-h** [comment]
Faz um tempo que abri essa issue com sugestão de melhorias. Atualmente, eu não acompanho mais o projeto. Não sei o estado da aplicação no momento. 

Imagino que já tenham implementado algo para melhorar ainda  performace. Assim, tornando irrelevante a issue.
