### ISSUE TITLE
Erro ao tentar usar mais de 50 cores

### ISSUE THREAD

**Issue by alexandrersa** [lmajowka/btcgo#20]
O código limita rodar a no máximo 50 cores, no entanto para máquinas mais parrudas, não é possível extrair todo o poder de processamento.

CPUs detectados: 56
Quantos CPUs gostaria de usar?: 56
Numero invalido.

**Comment by rafinhahdc19** [comment]
Já enviei um pull request com a alteração, agora é só esperar.

**Comment by lmajowka** [comment]
Ja foi mergeado @rafinhahdc19
