### ISSUE TITLE
Tem algum problema ao buscar a carteira

### ISSUE THREAD

**Issue by lucastoledo95** [lmajowka/btcgo#6]
Na primeira vez que eu rodei, eu percebi que a carteira estava diferente da carteira 4, mas tentei reproduzir abrindo logo de primeira mas não esta indo.

Segue :
![image](https://github.com/lmajowka/btcgo/assets/14190798/97c8b0fc-d46f-40e3-af79-9bf44e6ccbbf)

![image](https://github.com/lmajowka/btcgo/assets/14190798/b8f64d44-06b2-4098-bab9-976bcb4cc390)

**Comment by lmajowka** [comment]
Acontece nas carteiras pequenas, porque ele acha a 4, mas continua buscando, ai um outro worker pode achar a 5 antes
